### ISSUE TITLE
create new blog post template that doesn't require twitter handle

### ISSUE THREAD

**Issue by alicetragedy** [rails-girls-summer-of-code/summer-of-code#272]
Right now, the blog post template we use for all our blog posts requires a twitter handle in the front matter section; without it, it shows a weird comma after the author name. I've tried removing the comma in the current template (see `_layouts/post.html`) but it doesn't have an effect on how the author name is displayed, unfortunately. 

The easiest (= laziest) way to solve this would be IMO to create a new template that can be used by guest authors that don't have (or don't wish to publish) a twitter handle.

**Comment by carpodaster** [comment]
@alicetragedy I've just checked [the layout file](https://github.com/rails-girls-summer-of-code/summer-of-code/blob/gh-pages/_layouts/post.html#L12-L16): a twitter handle isn't mandatory, you can omit the twitter line in the frontmatter section.

**Comment by alicetragedy** [comment]
@carpodaster any suggestions on removing the strange floating comma if a twitter handle isn't added? That's actually the main problem there, it doesn't break Jekyll or anything — just adds this random comma and I was unable to get rid of it somehow.

**Comment by alicetragedy** [comment]
A picture is worth a thousand words ;)

![twitter-comma](https://cloud.githubusercontent.com/assets/3143348/18687113/edf911f8-7f7e-11e6-8bd9-c0f8cb459038.jpg)

**Comment by carpodaster** [comment]
@alicetragedy I think it's fixed now

**Comment by alicetragedy** [comment]
@carpodaster nope it's not :( 
As I already wrote in the original issue/comment, I'd tried doing that (removing the comma in the template) but it was hopeless. I don't know why removing the comma there doesn't work, but it still leaves us with a ghost comma 😱 👻  hence my suggestion to create a new template (The Lazy Way™️).
If anyone has any other suggestions though... Shoot away!

**Comment by carpodaster** [comment]
Oh, apologies – I didn't pay 100% attention to the initial issue comment. And stupid me: I did remove the comma from the layout file again yesterday, re-loaded the blog page and thought: oh look, no comma. Without realizing that the blog post I was looking at still had a twitter handle configured of course. /headdesk 🙃

I've checked it locally w/o twitter handle and it does seem to work:

![bildschirmfoto 2016-09-21 um 11 09 27](https://cloud.githubusercontent.com/assets/164400/18705046/dac97514-7fec-11e6-9931-1d7e23f36005.png)

**Comment by alicetragedy** [comment]
you're right @carpodaster — I was looking at the index, where the metadata still shows with a comma. on a single post however, it looks like in your screenshot. My fault! 
Now to see if there's a way to remove the comma in the main (= index) layout, and we're good to go! Sorry about the misunderstanding here.

**Comment by alicetragedy** [comment]
@carpodaster okay, fixed the above in 20d374de529c811682919b570be30489b699f454. I think we can close this now, thank you @carpodaster 🎉

**Comment by carpodaster** [comment]
A tricky: two commas!

> Always two there are, no more, no less.

**Comment by alicetragedy** [comment]
![image](https://cloud.githubusercontent.com/assets/3143348/18705592/242951be-7fef-11e6-806b-33cc894daed8.png)

**Comment by carpodaster** [comment]
Team Joda would approve of this conversation ;)
